name: prompts
version: 2.0.0
description: Rich, simple, synchronous command-line prompt library for Dart.
homepage: https://github.com/fwx5618177/prompts
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  charcode: ^1.2.0
  io: ^1.0.0
dev_dependencies:
  pedantic: ^1.11.0
